# Generated by Django 4.2.3 on 2023-07-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('curr_temp', models.CharField(max_length=100)),
                ('wind_speed', models.CharField(max_length=100)),
                ('weather_cond', models.CharField(max_length=100)),
            ],
        ),
    ]
